name: Playwright Tests Integration with Gmail
on:
  push:
    branches: [ master ]
  schedule:
    - cron: 30 5 * * 1-5
jobs:
  test:
    strategy:
        fail-fast: false #in this case if one job fails other won't get fail by default it is set to Pass
        max-parallel: 1 #it provide details how many parallel thread we want to run
        matrix:
          os: [ ubuntu-latest, windows-latest, macos-latest ]
    timeout-minutes: 60
    runs-on: ${{matrix.os}}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
      
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
      
    - name: Run Playwright tests
      run: npx playwright test

    - name: Job Dump
      env: 
        JOB_CONTEXT: ${{ toJson(job) }}
      run: echo "$JOB_CONTEXT"

    - name: Upload the artifact only for Ubuntu-latest
      if: matrix.os == "ubuntu-latest"
    - uses: actions/upload-artifact@v4
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
